# Generated by Django 4.0.2 on 2022-02-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.user'),
        ),
    ]
