# Generated by Django 4.0.2 on 2022-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_count_views',
            new_name='count_of_views',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(),
        ),
    ]
