# Generated by Django 4.0.2 on 2022-02-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_recipe_count_views_recipe_count_of_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='count_of_views',
            new_name='views',
        ),
    ]
